clear;clc;
Path = [cd,'\M2R\',];
FileName1O = dir([Path,'*1O.txt']);
FileName2O = dir([Path,'*2O.txt']);
FileName3O = dir([Path,'*3O.txt']);
FileName1D = dir([Path,'*1D.txt']);
FileName2D = dir([Path,'*2D.txt']);
FileName3D = dir([Path,'*3D.txt']);
C1_result_MIC = nirs_MIC(FileName1O,FileName1D,Path);
C2_result_MIC = nirs_MIC(FileName2O,FileName2D,Path);
C3_result_MIC = nirs_MIC(FileName3O,FileName3D,Path);
fig = figure;
C1_AVG_MIC = Struct_mean_nirsdata(C1_result_MIC);
C2_AVG_MIC = Struct_mean_nirsdata(C2_result_MIC);
C3_AVG_MIC = Struct_mean_nirsdata(C2_result_MIC);
subplot(1,3,1); imagesc(1:20, 1:20, C1_AVG_MIC.AVG_oxy); caxis([0.1 0.5]);
subplot(1,3,2); imagesc(1:20, 1:20, C2_AVG_MIC.AVG_oxy); caxis([0.1 0.5]);
subplot(1,3,3); imagesc(1:20, 1:20, C3_AVG_MIC.AVG_oxy); caxis([0.1 0.5]);
Result.MIC = nirs_statistical_test(C3_result_MIC,C1_result_MIC,5000,1);